new stuff!

diff --git a/scripts/passmenu2 b/scripts/passmenu2
--- a/scripts/passmenu2
+++ b/scripts/passmenu2
@@ -2,59 +2,27 @@
 
 shopt -s nullglob globstar
 
-typeit=0
-if [[ $1 == "--type" ]]; then
-	typeit=1
-	shift
+if [[ -n $WAYLAND_DISPLAY ]]; then
+	dmenu=dmenu-wl
+elif [[ -n $DISPLAY ]]; then
+	dmenu=dmenu
+else
+	echo "Error: No Wayland or X11 display detected" >&2
+	exit 1
 fi
 
+prefix=${PASSWORD_STORE_DIR-~/.password-store}
+password_files=( "$prefix"/**/*.gpg )
+password_files=( "${password_files[@]#"$prefix"/}" )
+password_files=( "${password_files[@]%.gpg}" )
 
-STARTDIR=${PASSWORD_STORE_DIR-~/.password-store}
-BASEDIR=$STARTDIR
-DONE=0
-LEVEL=0
-PREVSELECTION=""
-SELECTION=""
+if [ ${#password_files[@]} -eq 1 ]; then
+    password=${password_files[0]}
+else
+    password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")
+fi
 
-while [ "$DONE" -eq 0 ] ; do 
-  password_files=( "$STARTDIR"/* )
-  password_files=( "${password_files[@]#"$STARTDIR"/}" )
-  password_files=( "${password_files[@]%.gpg}" )
-  
-  if [ "$LEVEL" -ne 0 ] ; then
-    password_files=(".." "${password_files[@]}") 
-  fi
-  entry=$(printf '%s\n' "${password_files[@]}" | dmenu "$@" -l 15)
-  
-  echo "entry: $entry"
-  if [ -z "$entry" ] ; then
-    DONE=1
-    exit
-  fi
-  
-  if [ "$entry" != ".." ] ; then
-    PREVSELECTION=$SELECTION
-    SELECTION="$SELECTION/$entry"
-  
-    # check if another dir
-    if [ -d "$STARTDIR/$entry" ] ; then
-      STARTDIR="$STARTDIR/$entry"
-      LEVEL=$((LEVEL+1))
-    else
-      # not a directory so it must be a real password entry
-  
-      if [[ $typeit -eq 0 ]]; then
-        pass show -c "$SELECTION" 2>/dev/null
-      else
-        xdotool - <<<"type --clearmodifiers -- $(pass show "$SELECTION" | head -n 1)"
-      fi
-      DONE=1
-    fi
-  
-  else
-    LEVEL=$((LEVEL-1))
-    SELECTION=$PREVSELECTION
-    STARTDIR="$BASEDIR/$SELECTION"
-  fi
-done
+[[ -n $password ]] || exit
 
+echo "$password" 
+pass show "$password" 2>/dev/null
